## Import the libraries

In [119]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [120]:
dataset = pd.read_csv('./data/1000_Companies.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [121]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [122]:
X[:5, :]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [123]:
y[:5]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94])

## Preprocess data

In [124]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [125]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X_preprocessor = ColumnTransformer(
    remainder='passthrough',        # Keep data that isn't processed by the transformer
    transformers=[
        ('categorical', OneHotEncoder(drop='first'), [3])
    ])

In [126]:
X_train_encoded = np.array(X_preprocessor.fit_transform(X_train))
X_test_encoded = np.array(X_preprocessor.transform(X_test))

display(X_train_encoded[:5, :])

array([[0.0, 0.0, 92746.0, 124154.2473, 247732.6995],
       [0.0, 0.0, 106821.0, 126232.9075, 274890.4504],
       [1.0, 0.0, 29076.0, 114751.1717, 124881.2606],
       [1.0, 0.0, 87369.0, 123360.1475, 237357.7633],
       [1.0, 0.0, 154222.0, 133233.3031, 366350.8093]], dtype=object)

## Train the model

In [127]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=5)
regressor.fit(X_train_encoded, y_train)

DecisionTreeRegressor(max_depth=5)

## Evaluate model

In [128]:
train_accuracy = regressor.score(X_train_encoded, y_train)
print(f'Train accuracy = {round(train_accuracy, 4) * 100}%')

test_accuracy = regressor.score(X_test_encoded, y_test)
print(f'Test accuracy = {round(test_accuracy, 4) * 100}%')

Train accuracy = 99.72%
Test accuracy = 99.44%


## Predict

In [129]:
data = [
    [200000.0, 200000.0, 200000.0, 'New York'],
    [600000.0, 0.0, 0.0, 'California'],
    [0.0, 600000.0, 0.0, 'Florida'],
    [0.0, 0.0, 600000.0, 'New York']
]

In [130]:
data_scaled = X_preprocessor.transform(data)
y_pred = regressor.predict(data_scaled)

display(y_pred)

array([413956.48      , 174707.60564545,  39116.57      ,  78615.21654486])