# Decision Tree Regression

## Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [20]:
dataset = pd.read_csv('./data/1000_Companies.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [21]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [22]:
X[:5, :]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [23]:
y[:5]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94])

## Preprocess data

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/5, random_state = 100)

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

X_preprocessor = ColumnTransformer(
    remainder='passthrough',        # Keep data that isn't processed by the transformer
    transformers=[
        ('categorical', OneHotEncoder(drop='first'), [3])
    ])

In [26]:
X_train_encoded = np.array(X_preprocessor.fit_transform(X_train))
X_test_encoded = np.array(X_preprocessor.transform(X_test))

display(X_train_encoded[:5, :])

array([[1.0, 0.0, 12585.0, 112315.7057, 93061.83105],
       [1.0, 0.0, 113168.0, 127170.2613, 287137.0042],
       [0.0, 0.0, 82771.0, 122681.0939, 228485.9097],
       [0.0, 0.0, 156926.0, 133632.6421, 371568.1847],
       [1.0, 0.0, 49642.0, 117788.4523, 164563.4137]], dtype=object)

## Training the model

In [29]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=5, random_state = 0)
regressor.fit(X_train_encoded, y_train)

DecisionTreeRegressor(max_depth=5, random_state=0)

## Evaluate model

In [30]:
accuracy = regressor.score(X_test_encoded, y_test)
print(f'Accuracy = {round(accuracy, 4) * 100}%')

Accuracy = 99.18%


## Predict

In [31]:
data = [
    [200000.0, 200000.0, 200000.0, 'New York'],
    [600000.0, 0.0, 0.0, 'California'],
    [0.0, 600000.0, 0.0, 'Florida'],
    [0.0, 0.0, 600000.0, 'New York']
    ]

In [32]:
data_scaled = X_preprocessor.transform(data)
y_pred = regressor.predict(data_scaled)

display(y_pred)

array([413956.48      , 174117.4396898 ,  28620.565     ,  77974.77128094])