## Import the libraries

In [289]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import the dataset

In [290]:
dataset = pd.read_csv('./data/1000_Companies.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [291]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [292]:
X[:5, :]

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida']], dtype=object)

In [293]:
y[:5]

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94])

## Preprocess data

In [294]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [295]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X_preprocessor = ColumnTransformer(
    remainder='passthrough',
    transformers=[
        ('categorical', OneHotEncoder(drop='first'), [3])
    ])

In [296]:
X_train_encoded = np.array(X_preprocessor.fit_transform(X_train))
X_test_encoded = np.array(X_preprocessor.transform(X_test))

display(X_train_encoded[:5, :])

array([[1.0, 0.0, 103756.0, 125780.2543, 268976.5245],
       [0.0, 1.0, 16787.0, 112936.2762, 101169.6015],
       [0.0, 0.0, 62977.0, 119757.8258, 190293.3327],
       [0.0, 0.0, 107864.0, 126386.9425, 276902.9217],
       [1.0, 0.0, 105004.0, 125964.5646, 271384.5439]], dtype=object)

## Train the model

In [297]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 5, max_depth=5)
regressor.fit(X_train_encoded, y_train)

RandomForestRegressor(max_depth=5, n_estimators=5)

## Evaluate model

In [298]:
train_accuracy = regressor.score(X_train_encoded, y_train)
print(f'Train accuracy = {round(train_accuracy, 4) * 100}%')

test_accuracy = regressor.score(X_test_encoded, y_test)
print(f'Test accuracy = {round(test_accuracy, 4) * 100}%')

Train accuracy = 99.53999999999999%
Test accuracy = 99.48%


## Predict

In [299]:
data = [
    [200000.0, 200000.0, 200000.0, 'New York'],
    [600000.0, 0.0, 0.0, 'California'],
    [0.0, 600000.0, 0.0, 'Florida'],
    [0.0, 0.0, 600000.0, 'New York']
]

In [300]:
data_scaled = X_preprocessor.transform(data)
y_pred = regressor.predict(data_scaled)

display(y_pred)

array([287944.83523475, 178706.83899942,  34927.44512133,  64817.52619142])